import type { Metadata } from "next";
import { Mukta } from "next/font/google";
import "./globals.css";
import { LogoBarCompoent } from "@/components/logobar.compoent";
import { NavabrCompoent } from "@/components/navbar.compoent";
import { AdsViewComponent } from "@/components/ads-view.component";

const mukta = Mukta({ subsets: ['devanagari'], weight:"400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={mukta.className}>
        <LogoBarCompoent/>
        <NavabrCompoent />
        <AdsViewComponent/>
        {children}
        </body>
    </html>
  );
}
