import { Mukta } from "next/font/google";
import "./globals.css";
import { Metadata } from "next";

const mukta = Mukta({ subsets: ["devanagari"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mukta.className}>{children}</body>
    </html>
  );
}
