import { NavDashboard } from "@/components/dashboard/navbar.compoent";
import { DashbordSidebar } from "@/components/dashboard/sidebar.component";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="w-full">
        <NavDashboard />
        <div className="flex">
          <DashbordSidebar />
          <main className="w-full p-2">{children}</main>
        </div>
      </body>
    </html>
  );
}
